#!/bin/sh

previous="$(cliphist list | head -1 | awk '{$1=null; print $0}')"

cliphist store

current="$(cliphist list | head -1 | awk '{$1=null; print $0}')"

if [ "$current" != "$previous" ]; then
    cliphist list | head -1 | cliphist decode | wl-copy
fi
